services:
  backend:
    build:
      context: .
    secrets:
      - rpc-access-token
    environment:
      - RPC_ACCESS_TOKEN_PATH=/run/secrets/rpc-access-token
      - HTTP_PORT=8080
    ports:
      - 8080:8080

secrets:
  rpc-access-token:
    file: secrets/rpc-access-token
